server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://uop-dev-wx.cmcutmukkzyn.rds.cn-north-1.amazonaws.com.cn:3306/ltjtest
        username: root
        password: Bestv001!
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:com/didispace/test/dao/mapping/*.xml
  type-aliases-package: com.didispace.test.dao.impl

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql